export interface ILetter {
    id?: number,
    nombre: string,
    diasxaño: number,
    plazoTasa: string,
    tipoTasa: string,
    tasaEfect?: string,
    tasaNomi?: string,
    fechaDescuento: string,
    periodoCapi: string,
    fechaEmision: string,
    fechaVencimiento: string,
    valorNominal: number,
    retencion: number,
    CIMotivo?: string,
    CIExpresadoEn?: string,
    CFMotivo?: string,
    CFExpresadoEn?: string,
    descuento: number,
    tasaDescuento:number,
    valorEntregado: number,
    valorRecibido: number,
    valorNeto: number,
    TCEP:number,
    idUser: number
}